spring:
  application:
    name: smartbancs-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartbancs}
    username: ${SPRING_DATASOURCE_USERNAME:smartbancs}
    password: ${SPRING_DATASOURCE_PASSWORD:smartbancs}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  shutdown: graceful

springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: list

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics