spring:
  application:
    name: smartbancs-ai-service

server:
  port: 8081

springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: list

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}